
const EVENTS = {
  GET_POSTS: 'GET_POSTS',
  MORE_POSTS: 'MORE_POSTS',
  NEW_POST: 'NEW_POST',
  DELETE_POST: 'DELETE_POST',
  LIKE: 'LIKE',
  THEME_CHANGE: 'THEME_CHANGE',
  LOADING: event => `LOADING_${event}`
}

export default EVENTS